name: docker-compose-actions-test
on:
  push:
    branches:
      - 'feature/modify-helm-charts'
    paths-ignore:
      - 'DCOS/**'
      - 'K8s/**'
      - 'load-gen/**'
      - 'OpenShift/**'
      - 'Swarm/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Authenticate with GCP
      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GIT_ACTIONS_GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker us-east1-docker.pkg.dev
      
      # Build and Push Images
      - name: Build and Push Docker Images
        run: |
          export REPO=us-east1-docker.pkg.dev/graceful-byway-445402-q0/docker-image-repo
          export TAG=$(date +%Y%m%d%H%M%S) # Example: Use timestamp as the tag
          docker-compose build
          docker-compose push
