name: Security Scanning

on:
  push:
    branches:
      - "feature/modify-helm-charts"
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  trivy_scan:
    name: Run Trivy Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # File System scan and generate SBOM
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      # Container image scan
      - name: Build Docker Images
        run: |
          services=(cart catalogue dispatch payment ratings shipping user web)
          for service in "${services[@]}"; do
            docker build -t robot-shop/$service:latest ./$service
          done

      - name: Run Trivy Image Scans
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'image'
          image-ref: 'robot-shop/$service:latest'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

    # Upload Image Scan Results
      - name: Upload Image Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'

    # Run Trivy Config Scan for IaC
      - name: Run Trivy Config Scan
        run: |
         trivy config --severity CRITICAL,HIGH --format sarif --output trivy-config-results.sarif .

    # Upload Config Scan Results
      - name: Upload Config Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
         sarif_file: 'trivy-config-results.sarif'