name: Security Scanning

on:
  push:
    branches:
      - "feature/modify-helm-charts"
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  trivy_scan:
    name: Run Trivy Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # File System scan and generate SBOM
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy Image Scans
        run: |
            services=(cart catalogue dispatch payment ratings shipping user web)
            for service in "${services[@]}"; do
              echo "Scanning image robot-shop/$service:latest"
              if ! trivy image --severity CRITICAL,HIGH --ignore-unfixed --format sarif \
                  -o ./trivy-image-results-$service.sarif robot-shop/$service:latest; then
                echo "Trivy scan failed for robot-shop/$service:latest"
              fi
            done
        
      - name: Debug SARIF Files
        run: |
            ls -lah ./trivy-image-results-*.sarif || echo "No SARIF files found."
        
      - name: Upload Image Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: './trivy-image-results-*.sarif'
        

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
            scan-type: 'config'
            hide-progress: true
            format: 'sarif'
            output: 'trivy-config-results.sarif'
            severity: 'CRITICAL,HIGH'

    # Upload Config Scan Results
      - name: Upload Config Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
         sarif_file: 'trivy-config-results.sarif'